import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastProvider } from './components/toast';
import Topbar from "./components/layout/Topbar";
import Sidebar from "./components/layout/Sidebar";
import DisplayBar from "./components/layout/DisplayBar";
import DisplayMain from "./components/layout/DisplayMain";
import DashboardLayout from "./components/layout/DashboardLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ToastProvider>
          <div className="flex flex-col max-h-screen h-screen overflow-hidden">
            <Topbar className="flex-[0_0]" />
            <div className="flex-1 bg-transparent relative flex overflow-hidden">
              <Sidebar />
              <div className='w-full overflow-hidden flex flex-col p-2 bg-primary'>
                <main className="w-full flex-1 bg-secondary text-secondary-text border border-color-100 rounded-lg overflow-hidden flex flex-col">                  
                    {children} {/* middleware is protecting and redirecting to login, but my problem is /login page is rendring here at this children props so sidebar and topbar is visible at login route */}
                </main>
              </div>
            </div>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
